# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('total_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='tipo_asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignatura.TipoAsignatura'),
        ),
    ]
