# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
        ('asignatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.Docente'),
        ),
    ]
