# Generated by Django 2.0.4 on 2018-04-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignatura', '0002_materia_teacher'),
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.TimeField(verbose_name='Hora Inicio')),
                ('hour_end', models.TimeField(verbose_name='Hora Salida')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asignatura.Materia')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docente.Docente')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
    ]
