# Generated by Django 2.0.4 on 2018-04-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('1lunes', 'LUNES'), ('2martes', 'MARTES'), ('3miercoles', 'MIERCOLES'), ('4jueves', 'JUEVES'), ('5viernes', 'VIERNES'), ('6sabado', 'SABADO')], default='lunes', max_length=32, verbose_name='Día'),
        ),
    ]
