# Generated by Django 2.0.4 on 2018-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20180425_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='posted',
            field=models.BooleanField(default=True, verbose_name='Publicado ?'),
        ),
    ]
