# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.ContratoDocente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='teacher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.TipoDocente'),
        ),
        migrations.AddField(
            model_name='docente',
            name='work_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.CategoriaDocente'),
        ),
    ]
