# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
        ('investigacion_tutoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigaciondocente',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.Docente'),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.Docente'),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='eje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion_tutoria.EjeInvestigacion'),
        ),
    ]
