# Generated by Django 2.0.4 on 2018-04-18 18:00

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.IntegerField(default=base.models.AcademicAnnouncement.current_year)),
                ('year_end', models.IntegerField(default=base.models.AcademicAnnouncement.current_year)),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
            },
        ),
        migrations.CreateModel(
            name='AcademicCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Centro Academico')),
            ],
            options={
                'verbose_name': 'Centro Academico',
                'verbose_name_plural': 'Centros Academicos',
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Programa')),
                ('date_start', models.DateField(verbose_name='Fecha Inicio')),
                ('date_end', models.DateField(verbose_name='Fecha Fin')),
                ('annoncement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicAnnouncement')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicCenter')),
            ],
            options={
                'verbose_name': 'Programa Academico',
                'verbose_name_plural': 'Programas Academicos',
            },
        ),
    ]
