# Generated by Django 2.0.4 on 2018-04-18 19:17

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicannouncement',
            name='year_end',
            field=models.IntegerField(default=base.models.AcademicAnnouncement.current_year, verbose_name='Año Final'),
        ),
        migrations.AlterField(
            model_name='academicannouncement',
            name='year_start',
            field=models.IntegerField(default=base.models.AcademicAnnouncement.current_year, verbose_name='Año Inicial'),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='annoncement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicAnnouncement', verbose_name='Convocatoria'),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicCenter', verbose_name='Centro Academico'),
        ),
    ]
