# Generated by Django 2.0.4 on 2018-04-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180418_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Fecha Inicio')),
                ('date_end', models.DateField(verbose_name='Fecha Fin')),
                ('annoncement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicAnnouncement')),
            ],
            options={
                'verbose_name': 'Ciclo de Estudio',
                'verbose_name_plural': 'Ciclos de Estudio',
            },
        ),
    ]
