# Generated by Django 2.0.4 on 2018-04-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_academiccycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccycle',
            name='name',
            field=models.CharField(default='*', max_length=128, verbose_name='Ciclo de Estudio'),
        ),
    ]
